feat: show RSS memory usage and percentage of using it by heap used
wonderlandpark/dokdo pull request #12
Opened 2020-11-27 17:01 UTC by zero734kr

**Please describe the changes this PR makes and why it should be merged:**
Show RSS memory usage and heapUsed separated to know the state of memory more correctly with percentage.

**Status**

- [x] Code changes have been tested.

**Semantic versioning classification:**

- [x] This PR includes new feature, methods or parameters
  - [ ] This PR includes breaking changes (feature, methods, parameters removed or renamed)
- [ ] This PR **only** includes non-code(typo, documentation etc.) changes

2020-11-27 17:04 UTC, wonderlandpark requested changes
Before review cleanup code style

2020-11-27 17:04 UTC, wonderlandpark commented on src/commands/main.js
> +`
```suggestion
  let summary = `Dokdo v${version}, discord.js \`${parent.Discord.version}\`, \`Node.js ${process.version}\` on \`${process.platform}\`\nProcess started at ${dayjs(system.processReadyAt()).fromNow()}, bot was ready at ${dayjs(parent.client.readyAt).fromNow()}.\n`
```

2020-11-27 17:04 UTC, wonderlandpark commented on src/commands/main.js
> +Can see ${cache} in this shard.`
```suggestion
    summary += `Running on PID ${process.pid} for this client, and running on PID ${process.ppid} for the parent process.\n\nThis bot is sharded in ${Array.isArray(parent.client.shard.shards) ? parent.client.shard.shards.length : parent.client.shard.count} shard(s) and running in ${guilds} guild(s).\nCan see ${cache} in this client.`
```

2020-11-28 02:10 UTC, wonderlandpark commented on src/commands/main.js
> +`
@zero734kr Not resolved

2020-11-28 02:10 UTC, wonderlandpark commented on src/commands/main.js
> +Can see ${cache} in this shard.`
@zero734kr Not resolved

2020-11-28 02:25 UTC, wonderlandpark requested changes

2020-11-28 02:25 UTC, wonderlandpark commented on src/commands/main.js
> +  let summary = `Dokdo \`v${version}\`, discord.js \`${parent.Discord.version}\`, \`Node.js ${process.version}\` on \`${process.platform}\`\nProcess started at \`\`${dayjs(system.processReadyAt()).fr
```suggestion
  let summary = `Dokdo v${version}, discord.js \`${parent.Discord.version}\`, \`Node.js ${process.version}\` on \`${process.platform}\`\nProcess started at ${dayjs(system.processReadyAt()).fromNow()}, bot was ready at ${dayjs(parent.client.readyAt).fromNow()}.\n`
```

Please do not make change.

2020-11-28 02:25 UTC, wonderlandpark commented on src/commands/main.js
> +  } else summary += `Running on \`\`PID ${process.pid}\`\`\n\nThis bot is not sharded and can see ${cache}.`
```suggestion
    summary += `Running on PID ${process.pid} for this client, and running on PID ${process.ppid} for the parent process.\n\nThis bot is sharded in ${Array.isArray(parent.client.shard.shards) ? parent.client.shard.shards.length : parent.client.shard.count} shard(s) and running in ${guilds} guild(s).\nCan see ${cache} in this client.`
  } else summary += `Running on PID ${process.pid}\n\nThis bot is not sharded and can see ${cache}.`
```

2020-11-28 02:25 UTC, wonderlandpark commented on src/commands/main.js
> +  summary += `\nAverage websocket latency: \`\`${parent.client.ws.ping}ms\`\``
```suggestion
  summary += `\nAverage websocket latency: ${parent.client.ws.ping}ms`
```

2020-11-28 02:57 UTC, wonderlandpark requested changes

2020-11-28 02:57 UTC, wonderlandpark commented on src/commands/main.js
> +  const cache = `\`\`${parent.client.guilds.cache.size} guild(s)\`\` and \`\`${parent.client.users.cache.size} user(s)\`\``
```suggestion
  summary += `\nUsing ${system.memory().rss} physical memory at this process and ${system.memory().heapUsed} heap memory.\n`
  const cache = `${parent.client.guilds.cache.size} guild(s) and ${parent.client.users.cache.size} user(s)`
```

2020-11-28 16:26 UTC, zero734kr commented on src/commands/main.js
> +  const cache = `\`\`${parent.client.guilds.cache.size} guild(s)\`\` and \`\`${parent.client.users.cache.size} user(s)\`\``
I’m not understanding why RSS is the physical memory, because RSS is only **assigned** memory to process, and not using or physical memory

2020-11-28 16:28 UTC, wonderlandpark commented on src/commands/main.js
> +  const cache = `\`\`${parent.client.guilds.cache.size} guild(s)\`\` and \`\`${parent.client.users.cache.size} user(s)\`\``
Quoted from jishaku.

2020-11-28 16:32 UTC, zero734kr commented on src/commands/main.js
> +  const cache = `\`\`${parent.client.guilds.cache.size} guild(s)\`\` and \`\`${parent.client.users.cache.size} user(s)\`\``
I think **dokdo** is only *based* from Jishaku and not being ported javascript version of Jishaku. I not seeing any problems to put `Assigned` instead of `Physical Memory`

2020-11-28 16:35 UTC, wonderlandpark commented on src/commands/main.js
> +  const cache = `\`\`${parent.client.guilds.cache.size} guild(s)\`\` and \`\`${parent.client.users.cache.size} user(s)\`\``
Then there would be no problem to display as physical memory

2020-11-28 16:41 UTC, zero734kr commented on src/commands/main.js
> +  const cache = `\`\`${parent.client.guilds.cache.size} guild(s)\`\` and \`\`${parent.client.users.cache.size} user(s)\`\``
Yes, but I’m saying that we are not ported version of Jishaku, and we doesn’t need to display same as Jishaku for user/devs

2020-11-28 16:42 UTC, wonderlandpark commented
I feel like I couldn't accept this PR

2020-11-28 16:45 UTC, closed without merging