fix(processmanager): escape when 'content' parameter is empty
wonderlandpark/dokdo pull request #13
Opened 2020-11-27 21:42 UTC by zero734kr

**Please describe the changes this PR makes and why it should be merged:**
There is a error ``TypeError: content.match is not a function`` when user digits ``.dokdo shard``

**Status**

- [x] Code changes have been tested.

**Semantic versioning classification:**

- [x] This PR includes new feature, methods or parameters
  - [ ] This PR includes breaking changes (feature, methods, parameters removed or renamed)
- [ ] This PR **only** includes non-code(typo, documentation etc.) changes

2020-11-28 02:21 UTC, wonderlandpark requested changes

2020-11-28 02:21 UTC, wonderlandpark commented on src/commands/shard.js
> +  const result = await res.then(r => inspect(r, { depth: 1 })).catch(e => e.toString())
Should not inspect it.
Needs to add with other shards values

2020-11-28 02:21 UTC, wonderlandpark commented on src/utils/ProcessManager.js
> +    this.splitted = content ? content.match(new RegExp(`.{1,${this.limit}}`, 'gms')) : null || [' ']
`null` not expected

2020-11-28 16:33 UTC, wonderlandpark requested changes

2020-11-28 16:33 UTC, wonderlandpark commented on src/commands/shard.js
> +  const result = await res.catch(e => e.toString())
```suggestion
  const result = await res.then(r => r).catch(e => e)
```

Why are you making this change?

2020-11-28 16:33 UTC, wonderlandpark commented on src/utils/ProcessManager.js
> +    this.splitted = content ? content.match(new RegExp(`.{1,${this.limit}}`, 'gms')) : [' '] || [' ']
```suggestion
    this.splitted = content ? content.match(new RegExp(`.{1,${this.limit}}`, 'gms')) : [' ']
```

2020-11-28 16:38 UTC, zero734kr commented on src/commands/shard.js
> +  const result = await res.catch(e => e.toString())
```js
await (/* Promise-based Function */).then(r => r)
``` 
is equal to 
```js
await (/* Promise-based Function */)
``` and I’m stringifying error because ProcessManager is receiving error itself as instance of Error, and this is reason for not having a error message in Discord. The 'content' parameter needs to be string but Error is being passed.

2020-11-29 04:45 UTC, wonderlandpark requested changes

2020-11-29 04:45 UTC, wonderlandpark commented on src/utils/ProcessManager.js
> +    this.splitted = content ? content.match(new RegExp(`.{1,${this.limit}}`, 'gms')) : [' ']
```suggestion
    this.splitted = content.match(new RegExp(`.{1,${this.limit}}`, 'gms')) || [' ']
```

https://github.com/wonderlandpark/dokdo/blob/3b61669cff3713cb496e75a7016a38218f6092e0/src/utils/ProcessManager.js#L28

Will not cause error

2020-12-01 00:00 UTC, wonderlandpark requested changes

2020-12-02 14:06 UTC, zero734kr commented on src/utils/splitText.js
> +
Did you read my commit message?

2020-12-02 14:06 UTC, zero734kr commented on src/utils/splitText.js
> +
ESLint(or Standard) is throwing a error because mergeable inside object parameter

2020-12-02 14:08 UTC, zero734kr commented on src/utils/splitText.js
> +
That is, we need to use
```js
function splitText (text, { maxLength: 2000, char: '\n' } = {}) {
```
instead of
```js
function splitText (text, { maxLength = 2000, char = '\n' } = {}) {
```

2020-12-02 14:14 UTC, wonderlandpark commented
I think this issue is invalid

2020-12-02 14:15 UTC, closed without merging

2020-12-02 14:16 UTC, wonderlandpark commented
It's not invalid but it is already fixed in main branch. To prevent conflict I'm closing it. 

If you have any question feel free to contact Dokdo Team.