feat: use discord timestamp message formatting instead of dayjs
wonderlandpark/dokdo pull request #249
Opened 2021-07-16 03:07 UTC by KeepSOBP

**Please describe the changes this PR makes and why it should be merged:**

https://discord.com/developers/docs/reference#message-formatting-formats

![image](https://nyan.shx.gg/54nZFIy9f.png)

**Status**

- [x] Code changes have been tested.

**Semantic versioning classification:**

- [x] This PR includes new feature, methods or parameters
  - [ ] This PR includes breaking changes (feature, methods, parameters removed or renamed)
- [ ] This PR **only** includes non-code(typo, documentation etc.) changes

2021-07-16 06:01 UTC, mome0320 requested changes

2021-07-16 06:01 UTC, mome0320 commented on src/utils/system.js
> +    return ((new Date() - process.uptime() * 1000) / 1000).toFixed(0)
```suggestion
    return new Date() - process.uptime()
```

2021-07-16 06:06 UTC, mome0320 commented on src/utils/system.js
> +    return ((new Date() - process.uptime() * 1000) / 1000).toFixed(0)
I think revert is better

2021-07-16 07:09 UTC, wonderlandpark requested changes

2021-07-16 07:09 UTC, wonderlandpark commented on src/utils/system.js
> +    return ((new Date() - process.uptime() * 1000) / 1000).toFixed(0)
This is not really related to PR, but could you change this like below?
```suggestion
    return new Date(Date.now() - process.uptime() * 1000)
```

2021-07-16 07:12 UTC, wonderlandpark requested changes

2021-07-16 07:12 UTC, wonderlandpark commented on src/commands/main.js
> +  const makeRelativeTime = (time) => `<t:${time}:R>`
This would be better if you separate it into a util file.

Also, it would be better to pass date as an argument
```suggestion
  const makeRelativeTime = (date) => `<t:${Math.floor(d/1000)}:R>`
```

2021-07-16 07:57 UTC, KeepSOBP commented
Later. 💤

2021-07-16 09:17 UTC, mome0320 requested changes

2021-07-16 09:17 UTC, mome0320 commented on src/commands/main.js
> +  let summary = `Dokdo v${version}, discord.js \`${Discord.version}\`, \`Node.js ${process.version}\` on \`${process.platform}\`\nProcess started at ${makeRelativeTime(processReadyAt)}, bot was ready
```suggestion
  let summary = `Dokdo v${version}, discord.js \`${Discord.version}\`, \`Node.js ${process.version}\` on \`${process.platform}\`\nProcess started at ${makeRelativeTime(system.processReadyAt())}, bot was ready at ${makeRelativeTime(parent.client.readyTimestamp)}.\n`
```

2021-07-17 13:20 UTC, mome0320 requested changes

2021-07-17 13:20 UTC, mome0320 commented on src/utils/RelativeTime.js
> +}
```suggestion
  /**
   * @param {Date} date
   */
  module.exports = function relativeTime(date) {
    return `<t:${Math.floor(date / 1000)}:R>`
  }
```

2021-07-17 13:20 UTC, mome0320 commented on src/utils/RelativeTime.js
> +}
and rename file first Character lower case. because it's function. not class.

2021-07-17 13:56 UTC, mome0320 approved these changes

2021-07-17 17:03 UTC, mome0320 requested changes

2021-07-17 17:03 UTC, mome0320 commented on src/commands/main.js
> +  let summary = `Dokdo v${version}, discord.js \`${Discord.version}\`, \`Node.js ${process.version}\` on \`${process.platform}\`\nProcess started at ${relativeTime(system.processReadyAt())}, bot was
relativeTime must pass Date. Not Number(Timestamp)
So replace readyTimestamp to readyAt.

```suggestion
  let summary = `Dokdo v${version}, discord.js \`${Discord.version}\`, \`Node.js ${process.version}\` on \`${process.platform}\`\nProcess started at ${relativeTime(system.processReadyAt())}, bot was ready at ${relativeTime(parent.client.readyAt)}.\n`
```

2021-07-17 17:10 UTC, mome0320 requested changes

2021-07-17 17:10 UTC, mome0320 commented on src/utils/relativeTime.js
> +  return `<t:${Math.floor(date / 1000)}:R>`
```suggestion
  return `<t:${Math.floor(date.getTime() / 1000)}:R>`
```

2021-07-18 00:43 UTC, wonderlandpark commented
Thanks for your contribution. I will work on this after I merge it.

2021-07-18 00:43 UTC, wonderlandpark approved these changes

2021-07-18 00:44 UTC, merged