feat: isOwner option
wonderlandpark/dokdo pull request #368
Opened 2021-11-27 09:38 UTC by pikokr

**Please describe the changes this PR makes and why it should be merged:**

isOwner 옵션을 추가했습니다.

타입: `(user: Discord.User) => boolean|Promise<boolean>`

owners 리스트에 명령어를 사용한 유저가 없을 경우에 호출됩니다.

true를 반환할 시 dokdo 명령어를 사용할 수 있게 됩니다

**Status**

- [x] Code changes have been tested.

**Semantic versioning classification:**

- [x] This PR includes new feature, methods or parameters
  - [ ] This PR includes breaking changes (feature, methods, parameters removed or renamed)
- [ ] This PR **only** includes non-code(typo, documentation etc.) changes

2021-11-27 11:53 UTC, wonderlandpark requested changes
PR과 관련되지 않은 파일은 수정하시면 안됩니다. (yark.lock, package.json etc...)
다양한 변경사항이 있으시다면 최소 단위의 PR을 생성해주세요.

2022-01-07 13:06 UTC, pikokr commented
@wonderlandpark

2022-08-14 14:25 UTC, wonderlandpark approved these changes

2022-08-14 14:25 UTC, wonderlandpark commented
Finally I'm back!

2022-08-14 14:25 UTC, merged