deps: update djs to v14
wonderlandpark/dokdo pull request #500
Opened 2022-08-15 11:53 UTC by skinmaker1345

**Please describe the changes this PR makes and why it should be merged:**
This PR includes updating peer deps of djs to v14, thus making Dokdo compatible w/ discord.js v14.

**Status**
- [ ] Code changes have been tested.

**Semantic versioning classification:**

- [ ] This PR includes new feature, methods or parameters
- [ ] This PR includes breaking changes (feature, methods, parameters removed or renamed)
- [ ] This PR **only** includes non-code(typo, documentation etc.) changes

2022-08-15 12:17 UTC, wonderlandpark commented
:wave: Thanks for contributing Dokdo!

2022-08-18 14:31 UTC, wonderlandpark requested changes

2022-08-18 14:31 UTC, wonderlandpark commented on src/commands/cat.js
> +const { ButtonStyle } = require('discord.js')
```suggestion
```

2022-08-18 14:31 UTC, wonderlandpark commented on src/commands/cat.js
> +      { button: new Discord.ButtonBuilder().setStyle(ButtonStyle.Primary).setCustomId('dokdo$next').setLabel('Next'), action: ({ manager }) => manager.nextPage(), requirePage: true }
```suggestion
      { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Danger).setCustomId('dokdo$prev').setLabel('Prev'), action: ({ manager }) => manager.previousPage(), requirePage: true },
      { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Secondary).setCustomId('dokdo$stop').setLabel('Stop'), action: ({ manager }) => manager.destroy(), requirePage: true },
      { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Primary).setCustomId('dokdo$next').setLabel('Next'), action: ({ manager }) => manager.nextPage(), requirePage: true }
```

2022-08-18 14:31 UTC, wonderlandpark commented on src/commands/curl.js
> +const { ButtonStyle } = require('discord.js')
```suggestion
```

2022-08-18 14:31 UTC, wonderlandpark commented on src/commands/curl.js
> +    { button: new Discord.ButtonBuilder().setStyle(ButtonStyle.Success).setCustomId('dokdo$next').setLabel('Next'), action: ({ manager }) => manager.nextPage(), requirePage: true }
```suggestion
    { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Danger).setCustomId('dokdo$prev').setLabel('Prev'), action: ({ manager }) => manager.previousPage(), requirePage: true },
    { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Secondary).setCustomId('dokdo$stop').setLabel('Stop'), action: ({ manager }) => manager.destroy(), requirePage: true },
    { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Success).setCustomId('dokdo$next').setLabel('Next'), action: ({ manager }) => manager.nextPage(), requirePage: true }
```

2022-08-18 14:31 UTC, wonderlandpark commented on src/commands/exec.js
> +const { ButtonStyle } = require('discord.js')
```suggestion
```

2022-08-18 14:31 UTC, wonderlandpark commented on src/commands/exec.js
> +    { button: new Discord.ButtonBuilder().setStyle(ButtonStyle.Danger).setCustomId('dokdo$prev').setLabel('Prev'), action: ({ manager }) => manager.previousPage(), requirePage: true },
```suggestion
    { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Danger).setCustomId('dokdo$prev').setLabel('Prev'), action: ({ manager }) => manager.previousPage(), requirePage: true },
```

2022-08-18 14:31 UTC, wonderlandpark commented on src/commands/exec.js
> +      button: new Discord.ButtonBuilder().setStyle(ButtonStyle.Secondary).setCustomId('dokdo$stop').setLabel('Stop'),
```suggestion
      button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Secondary).setCustomId('dokdo$stop').setLabel('Stop'),
```

2022-08-18 14:31 UTC, wonderlandpark commented on src/commands/exec.js
> +    { button: new Discord.ButtonBuilder().setStyle(ButtonStyle.Success).setCustomId('dokdo$next').setLabel('Next'), action: ({ manager }) => manager.nextPage(), requirePage: true }
```suggestion
    { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Success).setCustomId('dokdo$next').setLabel('Next'), action: ({ manager }) => manager.nextPage(), requirePage: true }
```

2022-08-18 14:31 UTC, wonderlandpark commented on src/commands/js.js
> +const { ButtonStyle } = require('discord.js')
```suggestion
```

2022-08-18 14:31 UTC, wonderlandpark commented on src/commands/js.js
> +    { button: new Discord.ButtonBuilder().setStyle(ButtonStyle.Success).setCustomId('dokdo$next').setLabel('Next'), action: ({ manager }) => manager.nextPage(), requirePage: true }
```suggestion
    { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Danger).setCustomId('dokdo$prev').setLabel('Prev'), action: ({ manager }) => manager.previousPage(), requirePage: true },
    { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Secondary).setCustomId('dokdo$stop').setLabel('Stop'), action: ({ manager }) => manager.destroy(), requirePage: true },
    { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Success).setCustomId('dokdo$next').setLabel('Next'), action: ({ manager }) => manager.nextPage(), requirePage: true }
```

2022-08-18 14:31 UTC, wonderlandpark commented on src/commands/jsi.js
> +const { ButtonStyle } = require('discord.js')
```suggestion
```

2022-08-18 14:31 UTC, wonderlandpark commented on src/commands/jsi.js
> +    { button: new Discord.ButtonBuilder().setStyle(ButtonStyle.Success).setCustomId('dokdo$next').setLabel('Next'), action: ({ manager }) => manager.nextPage(), requirePage: true }
```suggestion
    { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Danger).setCustomId('dokdo$prev').setLabel('Prev'), action: ({ manager }) => manager.previousPage(), requirePage: true },
    { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Secondary).setCustomId('dokdo$stop').setLabel('Stop'), action: ({ manager }) => manager.destroy(), requirePage: true },
    { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Success).setCustomId('dokdo$next').setLabel('Next'), action: ({ manager }) => manager.nextPage(), requirePage: true }
```

2022-08-18 14:31 UTC, wonderlandpark commented on src/commands/shard.js
> +const { ButtonStyle } = require('discord.js')
```suggestion
```

2022-08-18 14:31 UTC, wonderlandpark commented on src/commands/shard.js
> +    { button: new Discord.ButtonBuilder().setStyle(ButtonStyle.Success).setCustomId('dokdo$next').setLabel('Next'), action: ({ manager }) => manager.nextPage(), requirePage: true }
```suggestion
    { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Primary).setCustomId('dokdo$prev').setLabel('Prev'), action: ({ manager }) => manager.previousPage(), requirePage: true },
    { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Secondary).setCustomId('dokdo$stop').setLabel('Stop'), action: ({ manager }) => manager.destroy(), requirePage: true },
    { button: new Discord.ButtonBuilder().setStyle(Discord.ButtonStyle.Success).setCustomId('dokdo$next').setLabel('Next'), action: ({ manager }) => manager.nextPage(), requirePage: true }
```

2022-08-18 14:31 UTC, wonderlandpark commented on src/utils/ProcessManager.js
> +    return messages.concat(msg).filter(m => m)
Is this code written by your self or is it from the original DJS source code?

2022-08-18 14:31 UTC, wonderlandpark commented on src/utils/codeBlock.js
> +${escapeCodeBlock(content)}
Btw looks like this code change isn't really related to this PR.

2022-08-18 14:32 UTC, wonderlandpark commented
+ looks like lock file needs a update (djsv14)

2022-08-18 14:49 UTC, skinmaker1345 commented on src/utils/ProcessManager.js
> +    return messages.concat(msg).filter(m => m)
It is from the original DJS code, removed unnecessary checks.

2022-08-18 14:51 UTC, skinmaker1345 commented on src/utils/codeBlock.js
> +${escapeCodeBlock(content)}
Actually, discord.js removed Util. instead, the method which Util contained can be imported directly.

2022-08-21 02:20 UTC, wonderlandpark approved these changes
lgtm

2022-08-21 02:22 UTC, merged